# Generated by Django 4.2.4 on 2023-10-09 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0007_tutoruser_alter_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tutoruser',
            name='day_of_week',
        ),
        migrations.RemoveField(
            model_name='tutoruser',
            name='instructor_name',
        ),
    ]
