# Generated by Django 4.2.4 on 2023-10-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0009_delete_tutoruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(max_length=80)),
                ('student_name', models.CharField(max_length=100)),
                ('students_email', models.EmailField(max_length=100)),
            ],
        ),
    ]
