# Generated by Django 4.2.4 on 2023-10-13 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0013_alter_tutorschedule_subject_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.CharField(max_length=80)),
                ('question_asked', models.TimeField()),
                ('question_answered', models.TimeField()),
                ('instructor', models.CharField(max_length=100)),
                ('subject_area', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='session',
            name='questions_answered',
        ),
    ]
