# Generated by Django 4.2.4 on 2023-10-08 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0003_tutorschedule_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorschedule',
            name='room',
            field=models.CharField(max_length=80),
        ),
    ]
