# Generated by Django 4.2.4 on 2023-10-09 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0006_alter_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='TutorUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instructor_name', models.CharField(max_length=100)),
                ('day_of_week', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='session',
            name='instructor',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='session',
            name='room_no',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='session',
            name='session_time',
            field=models.TimeField(),
        ),
    ]
