# Generated by Django 4.2.4 on 2023-10-09 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0010_students'),
    ]

    operations = [
        migrations.RenameField(
            model_name='students',
            old_name='students_email',
            new_name='student_email',
        ),
    ]
