# Generated by Django 4.2.4 on 2023-10-13 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brightBoostApp', '0011_rename_students_email_students_student_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorschedule',
            name='subject_area',
            field=models.CharField(default='Maths', max_length=100),
        ),
    ]
